apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: metrics-platform
data:
  QUARKUS_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/metrics"
  QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: "update"
  QUARKUS_LOG_LEVEL: "INFO"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: metrics-platform
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
