apiVersion: v1
kind: Service
metadata:
  name: metrics-api
  namespace: metrics-platform
spec:
  type: NodePort
  selector:
    app: metrics-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
